name: tiq
description: WM tasks automation.

version: 1.0.2+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.13.0
  intl: ^0.17.0
  logging: ^1.0.0
  path: ^1.8.0
  path_provider: ^1.6.27
  rxdart: ^0.26.0
  tweetnacl: ^0.3.2
  uuid: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/CloudsEnergyTextLogo_sm.jpg
